root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/builder ./cmd/hgmx/builder"
  bin = "./tmp/builder"
  include_ext = ["go", "templ", "css", "js"]
  exclude_dir = ["tmp", "vendor", "node_modules", "cmd/hgmx/main"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
  delay = 1000

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[run]
  cmd = "./tmp/builder"
