env:
  - CGO_ENABLED=0

builds:
  - id: hgmx
    main: ./cmd/hgmx
    binary: hgmx
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: hgmx-archive
    builds:
      - hgmx
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "(?i)^docs?:"
      - "(?i)^test:"
      - Merge pull request
      - Merge branch

signs:
  - id: cosign
    cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "--key=env://COSIGN_PRIVATE_KEY"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: checksum

release:
  name_template: "{{.Tag}}"
